# Generated by Django 3.2.9 on 2021-12-15 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astator', '0005_alter_user_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='script',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
