# Generated by Django 3.2.9 on 2021-12-15 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astator', '0006_alter_script_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='script',
            name='category',
            field=models.CharField(choices=[('Adventure', 'Adventure'), ('Comedy', 'Comedy'), ('Epic', 'Epic'), ('Erotica', 'Erotica'), ('Fairy Tale', 'Fairy Tale'), ('Fantasy', 'Fantasy'), ('Historical Fiction', 'Historical Fiction'), ('Horror', 'Horror'), ('Mystery', 'Mystery'), ('Romance', 'Romance'), ('Satire', 'Satire'), ('Science Fiction', 'Science Fiction'), ('Thriller', 'Thriller')], max_length=25),
        ),
    ]
