# Generated by Django 3.2.9 on 2021-12-15 17:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astator', '0007_alter_script_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='script',
            name='upload',
            field=models.FileField(upload_to='scripts/%Y/%m/%D/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['doc', 'docx'])], verbose_name='Select your script'),
        ),
    ]
