# Generated by Django 3.2.9 on 2021-12-16 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astator', '0008_alter_script_upload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='script',
            name='cover',
            field=models.ImageField(blank=True, default='default_cover_pic.png', upload_to='covers/%Y/%m/%D/', verbose_name='Select your cover image(optional)'),
        ),
    ]
