# Generated by Django 3.2.9 on 2021-12-17 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astator', '0009_alter_script_cover'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='author',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='bio',
            field=models.TextField(blank=True),
        ),
    ]
