# Generated by Django 3.2.9 on 2021-12-18 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astator', '0011_user_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(default='<bound method Field.value_to_string of <django.db.models.fields.CharField>> <bound method Field.value_to_string of <django.db.models.fields.CharField>>', max_length=200),
        ),
    ]
