# Generated by Django 3.2.9 on 2021-12-18 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astator', '0012_alter_user_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(default='<bound method Field.value_from_object of <django.db.models.fields.CharField>> <bound method Field.value_from_object of <django.db.models.fields.CharField>>', max_length=200),
        ),
    ]
