# Generated by Django 3.2.9 on 2021-12-19 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astator', '0015_auto_20211219_1548'),
    ]

    operations = [
        migrations.AlterField(
            model_name='script',
            name='category',
            field=models.CharField(choices=[('Adventure', 'Adventure'), ('Comedy', 'Comedy'), ('Epic', 'Epic'), ('Erotica', 'Erotica'), ('Fairy_Tale', 'Fairy_Tale'), ('Fantasy', 'Fantasy'), ('Historical_Fiction', 'Historical_Fiction'), ('Horror', 'Horror'), ('Mystery', 'Mystery'), ('Romance', 'Romance'), ('Satire', 'Satire'), ('Science_Fiction', 'Science_Fiction'), ('Thriller', 'Thriller')], max_length=25),
        ),
        migrations.AlterField(
            model_name='script',
            name='script_type',
            field=models.CharField(choices=[('Concept', 'Concept'), ('Draft', 'Draft'), ('Short_Story', 'Short_Story')], max_length=20),
        ),
    ]
