# Generated by Django 3.2.9 on 2021-12-20 10:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astator', '0017_auto_20211219_1557'),
    ]

    operations = [
        migrations.AlterField(
            model_name='script',
            name='upload',
            field=models.FileField(upload_to='scripts/%Y/%m/%D/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['docx'])], verbose_name='Select your script'),
        ),
    ]
