# Generated by Django 3.2.9 on 2021-12-21 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astator', '0019_auto_20211220_1727'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='source',
            field=models.TextField(null=True),
        ),
    ]
