# Generated by Django 3.2.9 on 2021-12-22 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('astator', '0021_auto_20211222_1054'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Sugestion',
            new_name='Suggestion',
        ),
    ]
